export type BinarySensor = {
  objectId: number;
};

export const BatteryHigh: BinarySensor = {objectId: 0x15};
export const BatteryCharging: BinarySensor = {objectId: 0x16};
export const CarbonMonoxide: BinarySensor = {objectId: 0x17};
export const Cold: BinarySensor = {objectId: 0x18};
export const Connectivity: BinarySensor = {objectId: 0x19};
export const Door: BinarySensor = {objectId: 0x1a};
export const GarageDoor: BinarySensor = {objectId: 0x1b};
export const Gas: BinarySensor = {objectId: 0x1c};
export const GenericBoolean: BinarySensor = {objectId: 0x0f};
export const Heat: BinarySensor = {objectId: 0x1d};
export const Light: BinarySensor = {objectId: 0x1e};
export const Lock: BinarySensor = {objectId: 0x1f};
export const MoistureWet: BinarySensor = {objectId: 0x20};
export const Motion: BinarySensor = {objectId: 0x21};
export const Moving: BinarySensor = {objectId: 0x22};
export const Occupancy: BinarySensor = {objectId: 0x23};
export const Opening: BinarySensor = {objectId: 0x11};
export const Plug: BinarySensor = {objectId: 0x24};
export const PowerOn: BinarySensor = {objectId: 0x10};
export const Presence: BinarySensor = {objectId: 0x25};
export const Problem: BinarySensor = {objectId: 0x26};
export const Running: BinarySensor = {objectId: 0x27};
export const Safety: BinarySensor = {objectId: 0x28};
export const Smoke: BinarySensor = {objectId: 0x29};
export const Sound: BinarySensor = {objectId: 0x2a};
export const Tamper: BinarySensor = {objectId: 0x2b};
export const Vibration: BinarySensor = {objectId: 0x2c};
export const Window: BinarySensor = {objectId: 0x2d};
